apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-service
  name: my-service
spec:
  ports:
    - nodePort: 31289
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-service
  type: LoadBalancer